# Generated by Django 6.0.7 on 2026-08-15 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hms_app', '0002_remove_room_patient_alter_room_status_bed'),
    ]

    operations = [
        migrations.AddField(
            model_name='bed',
            name='category',
            field=models.CharField(choices=[('General', 'General'), ('Economy', 'Economy'), ('2 Sharing', '2 Sharing'), ('3 Sharing', '3 Sharing'), ('4 Sharing', '4 Sharing'), ('5 Sharing', '5 Sharing'), ('Economy Premium', 'Economy Premium'), ('Premium', 'Premium')], default='General', max_length=30),
        ),
    ]
