# Generated by Django 6.0.7 on 2026-08-15 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hms_app', '0003_bed_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='staff_id',
            field=models.CharField(blank=True, help_text='Required for all staff roles', max_length=50, null=True),
        ),
    ]
