# Generated by Django 6.0.7 on 2026-08-15 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hms_app', '0006_alter_bed_category_alter_room_room_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bed',
            name='category',
            field=models.CharField(choices=[('General Ward', 'General Ward'), ('Economy', 'Economy'), ('2 Sharing', '2 Sharing'), ('3 Sharing', '3 Sharing'), ('4 Sharing', '4 Sharing'), ('5 Sharing', '5 Sharing'), ('Economy Premium', 'Economy Premium'), ('Premium', 'Premium'), ('Standard Private', 'Standard Private'), ('Deluxe Private', 'Deluxe Private'), ('Super Deluxe Private', 'Super Deluxe Private'), ('Suite', 'Suite'), ('ICU', 'ICU')], default='General', max_length=30),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_type',
            field=models.CharField(choices=[('General Ward', 'General Ward'), ('Standard Private', 'Standard Private'), ('Deluxe Private', 'Deluxe Private'), ('Super Deluxe Private', 'Super Deluxe Private'), ('Suite', 'Suite'), ('ICU', 'ICU')], max_length=50),
        ),
    ]
