# Generated by Django 6.0.7 on 2026-08-15 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hms_app', '0007_alter_bed_category_alter_room_room_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='private_category',
            field=models.CharField(blank=True, choices=[('Standard Private', 'Standard Private'), ('Deluxe Private', 'Deluxe Private'), ('Super Deluxe Private', 'Super Deluxe Private'), ('Suite', 'Suite')], help_text='Required if Room Type is Private.', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_type',
            field=models.CharField(choices=[('General Ward', 'General Ward'), ('Private', 'Private'), ('ICU', 'ICU')], max_length=50),
        ),
    ]
