# Generated by Django 6.0.7 on 2026-08-15 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hms_app', '0008_room_private_category_alter_room_room_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomPricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('General Ward', 'General Ward'), ('Standard Private', 'Standard Private'), ('Deluxe Private', 'Deluxe Private'), ('Super Deluxe Private', 'Super Deluxe Private'), ('Suite', 'Suite'), ('ICU', 'ICU')], max_length=50, unique=True)),
                ('daily_charge', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='room',
            name='charges',
        ),
    ]
