# Generated by Django 6.0.7 on 2026-08-16 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hms_app', '0009_roompricing_remove_room_charges'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorprofile',
            name='shift',
            field=models.CharField(choices=[('Morning', 'Morning (08:00 - 16:00)'), ('Evening', 'Evening (16:00 - 00:00)'), ('Night', 'Night (00:00 - 08:00)')], default='Morning', max_length=20),
        ),
    ]
