# Generated by Django 6.0.7 on 2026-08-16 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hms_app', '0011_userprofile_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='room_type',
            field=models.CharField(choices=[('Emergency Ward', 'Emergency Ward'), ('General Ward', 'General Ward'), ('Private', 'Private'), ('ICU', 'ICU')], max_length=50),
        ),
        migrations.AlterField(
            model_name='roompricing',
            name='category',
            field=models.CharField(choices=[('Emergency Ward', 'Emergency Ward'), ('General Ward', 'General Ward'), ('Standard Private', 'Standard Private'), ('Deluxe Private', 'Deluxe Private'), ('Super Deluxe Private', 'Super Deluxe Private'), ('Suite', 'Suite'), ('ICU', 'ICU')], max_length=50, unique=True),
        ),
    ]
