# Generated by Django 6.0.7 on 2026-08-16 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hms_app', '0012_alter_room_room_type_alter_roompricing_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='bed',
            name='medical_case',
            field=models.TextField(blank=True, help_text='Reason for admission / current case', null=True),
        ),
    ]
